pimcore:
    models:
        class_overrides:
            Pimcore\Model\DataObject\Car: AppBundle\Model\Product\Car
            Pimcore\Model\DataObject\AccessoryPart: AppBundle\Model\Product\AccessoryPart
            Pimcore\Model\DataObject\Category: AppBundle\Model\Product\Category


pimcore_ecommerce_framework:

    environment:
        # TODO integrate that implementation into core
        environment_id: AppBundle\Ecommerce\Overrides\Environment

    # Configuration of price systems - key is name of price system
    price_systems:
        default:
            # Price system defined and configured as container service
            id: app.default_price_system

    index_service:
        tenants:
            default:
                config_id: AppBundle\Ecommerce\IndexService\Config\MySqlConfig
                worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\DefaultMysql
                attributes:
                    name:
                        type: varchar(255)
                        filter_group: string
                    manufacturer:
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\DefaultObjects
                        filter_group: relation
                    bodyStyle:
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\DefaultObjects
                        filter_group: relation
                    carClass:
                        type: varchar(255)
                        filter_group: string
                    color:
                        type: varchar(255)
                        filter_group: multiselect
                    country:
                        type: varchar(255)
                        filter_group: string
                    milage:
                        type: double
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\QuantityValue
                        interpreter_options:
                            onlyValue: true
                        filtergroup: double
                    length:
                        type: double
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\QuantityValue
                        interpreter_options:
                            onlyValue: true
                        getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequence
                        getter_options:
                            source:
                                - brickfield: attributes
                                  bricktype: dimensions
                                  fieldname: length
                        filtergroup: double
                    width:
                        type: double
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\QuantityValue
                        interpreter_options:
                            onlyValue: true
                        getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequence
                        getter_options:
                            source:
                                - brickfield: attributes
                                  bricktype: dimensions
                                  fieldname: width
                        filtergroup: double
                    wheelbase:
                        type: double
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\QuantityValue
                        interpreter_options:
                            onlyValue: true
                        getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequence
                        getter_options:
                            source:
                                - brickfield: attributes
                                  bricktype: dimensions
                                  fieldname: wheelbase
                        filtergroup: double
                    weight:
                        type: double
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\QuantityValue
                        interpreter_options:
                            onlyValue: true
                        getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequence
                        getter_options:
                            source:
                                - brickfield: attributes
                                  bricktype: dimensions
                                  fieldname: weight
                        filtergroup: double

    filter_service:

        # Configure assortment tenants - at least one tenant has to be configured
        # If a _defaults key is set, it will be merged into every tenant.
        tenants:
            default:
                # Assign backend implementations and views to filter type field collections
                filter_types:
                    FilterInputfield:
                        # Service id for filter type implementation
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Input
                        # Default template for filter, can be overwritten in filter definition
                        template: 'shop/filters/input.html.twig'

                    FilterNumberRange:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRange
                        template: 'shop/filters/numberrange.html.twig'

                    FilterNumberRangeSelection:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRangeSelection
                        template: 'shop/filters/numberrange_select.html.twig'

                    FilterSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Select
                        template: 'shop/filters/select.html.twig'

                    FilterSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectFromMultiSelect
                        template: 'shop/filters/select.html.twig'

                    FilterMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelect
                        template: 'shop/filters/multi_select.html.twig'

                    FilterMultiSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectFromMultiSelect
                        template: 'shop/filters/multi_select.html.twig'

                    FilterMultiRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\MultiSelectRelation
                        template: 'shop/filters/multi_relation.html.twig'

                    FilterCategory:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectCategory
                        template: 'shop/filters/select_category.html.twig'

                    FilterRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SelectRelation
                        template: 'shop/filters/object_relation.html.twig'


    cart_manager:
        tenants:
            default:
                price_calculator:
                    modificators:
                        shipping:
                            class: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\CartPriceModificator\Shipping
                            # configuration options for price modificator
                            options:
                                charge: "5.90"

services:

    _defaults:
        autowire: true
        autoconfigure: true

    # Custom service definitions for index service
    AppBundle\Ecommerce\IndexService\Config\MySqlConfig:
        parent: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\AbstractConfig
        autowire: true
        autoconfigure: false

    # define own price system service and configure options for attribute name and price object class
    app.default_price_system:
        class: Pimcore\Bundle\EcommerceFrameworkBundle\PriceSystem\AttributePriceSystem
        arguments:
            $options:
                attribute_name: price


    Pimcore\Localization\IntlFormatter:
        calls:
            - [setCurrencyFormat, ['en', '造造 #,##0.00']]
            - [setCurrencyFormat, ['de', '#,##0.00 造造']]

    AppBundle\Ecommerce\Overrides\Environment:
        parent: Pimcore\Bundle\EcommerceFrameworkBundle\Environment
        autowire: true
        autoconfigure: false
