services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']


    AppBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']


    AppBundle\Twig\Extension\CategoryFilterExtension:
        tags: ['twig.extension']

    AppBundle\Twig\Extension\GeneralFilterExtension:
        tags: ['twig.extension']

    AppBundle\Twig\Extension\NavigationExtension:
        tags: ['twig.extension']

    AppBundle\Twig\Extension\UniqidExtension:
        tags: ['twig.extension']

    AppBundle\Website\LinkGenerator\CategoryLinkGenerator:
        public: true


    Pimcore\Templating\Helper\PimcoreUrl:
        class: AppBundle\Website\Tool\PimcoreUrl
        arguments:
            $generator: '@router'
        tags:
            - { name: templating.helper, alias: pimcoreUrl }

    AppBundle\EventListener\NameSettingListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd, method: onPreAdd }